name: BMS Selenium Tests

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:
    inputs:
      target_browser:
        description: 'Browser to test'
        type: choice
        options:
          - chrome
          - firefox
          - edge
        default: chrome
      target_env:
        description: 'Environment to test'
        type: choice
        options:
          - stage
          - prod
          - dev
        default: stage

jobs:
  run-test:
    runs-on: ubuntu-latest
    environment: ${{ inputs.target_env }}
    env:
      BROWSER: ${{ inputs.target_browser }}
      MONGO_URI: ${{ secrets.MONGO_URI }}
      USER_EMAIL : ${{ secrets.USER_EMAIL }}
      USER_PASSWORD : ${{ secrets.USER_EMAIL }}
      ADMIN_EMAIL : ${{ secrets.ADMIN_EMAIL }}
      ADMIN_PASSWORD : ${{ secrets.ADMIN_PASSWORD }}
      PARTNER_EMAIL : ${{ secrets.PARTNER_EMAIL }}
      PARTNER_PASSWORD : ${{ secrets.PARTNER_PASSWORD }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: setup jdk
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven

      - name: Run Selenium Tests
        run: mvn clean test -Dheadless=true -Dbrowser=$BROWSER

      - name: Upload Extent Reports
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: extent-reports
          path: |
            target/
            extent-reports/ExtentReport*.html
          retention-days: 30
